const actionNames = {
	CLEAR_VALIDATION_RESULT: 'CLEAR_VALIDATION_RESULT',
	GET_PACKAGES: 'GET_PACKAGES',
	RESET_STATE: 'RESET_STATE',
	SET_PACKAGES: 'SET_PACKAGES',
	SET_VALIDATION_RESULT: 'SET_VALIDATION_RESULT'
};

export default actionNames;
